[package]
name = "sov-state"
resolver = "2"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
anyhow = { workspace = true }
jmt = { workspace = true }

sov-modules-core = { path = "../sov-modules-core" }

[features]
default = []
