[package]
name = "sov-schema-db"
resolver = "2"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
rocksdb = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }

[features]
default = []